// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using News_Manager.Data;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace News_Manager.Migrations
{
    [DbContext(typeof(NewsDbContext))]
    partial class NewsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("News_Manager.Models.News", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NM_AUTOR");

                    b.Property<int>("Category")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("NR_CATEGORIA");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("CLOB")
                        .HasColumnName("TX_CONTEUDO");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ST_PUBLICADO");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("DATE")
                        .HasColumnName("DT_PUBLICACAO");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("DS_TITULO");

                    b.HasKey("Id");

                    b.ToTable("TBL_NEWS", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
